# fly.toml file generated for   on 2023-03-23T20:35:21Z

app = ""
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"
processes = []

[env]
  RABBITMQ_MNESIA_DIR = "/var/lib/rabbitmq/mnesia/data"

[[build]]
  image = "imgineapi/imagineapi-rabbitmq:0.1"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/var/lib/rabbitmq/mnesia"
  source = "rabbitmq"

[[services]]
  http_checks = []
  internal_port = 5672
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[services]]
  http_checks = []
  internal_port = 15672
  protocol = "tcp"
  script_checks = []

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
