# fly.toml file generated for  on 2023-03-23T20:39:33Z

app = ""
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"
processes = []

[[build]]
  image = "imgineapi/imagineapi-bot:0.1"

[env]
  RABBITMQ_PORT = 5672
  SERVICE_NAME = "consumer"

[experimental]
  auto_rollback = true

[mounts]
  destination = "/usr/src/app/logs"
  source = "bot"

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.health_checks]]
    command = "npx playwright test health_check.spec.js"
    interval = 10000
    timeout = 2000
    type = "script"
