# fly.toml file generated for  on 2023-03-23T20:38:02Z

app = ""
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "lax"
processes = []

[env]
  CONSUMER_ROLE_ID = "28cd8ba9-5485-4f52-80e6-04c91c827b09"
  DB_CLIENT = "postgres"
  DB_PORT = 5432
  DB_USER = "postgres"
  RABBITMQ_PORT = 5672
  STANDARD_ROLE_ID = "09c04dcf-5a1b-4583-b900-b259fa32dffa"

[experimental]
  auto_rollback = true

[mounts]
  destination = "/directus/uploads"
  source = "api"

[[services]]
  http_checks = []
  internal_port = 8055
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
